In [ ]:
# Basics of matrix 
"""
(6,)                    → 1 dimension, 6 items
(2, 3)                  → 2 dimensions, 2 rows × 3 columns
(2, 3, 4)               → 3 dimensions, 2 × 3 × 4
reshape(2, 3)           → 2 rows , 3 columns 
                        2 rows
                        ↓
                        [10 20 30]   ← row 1
                        [40 50 60]   ← row 2
reshape(1, -1)          → We have 6 numbers (10,20,30,40,50,60) so now (1,-1) means 1 row and how many we need 6 to make up to 6 numbers so 
                        1 row × 6 columns
                        [[10 20 30 40 50 60]]
reshape(2,-1)           → It will be 2 rows and how many we need now out of 6 -- 3 columns to build this matrix ( 6/2 = 3)
                        [[10 20 30]
                        [40 50 60]]
reshape() is just preparing the data for cosine_similarity(). It does not improve, change, or calculate the similarity itself.
"""

In [ ]:
from sentence_transformers import SentenceTransformer
# Below is OpenAI embeeding model ,since it is paid, we will use SentenceTransformer open source model 
"""
def get_embedding(text):
    response = client.embeddings.create(
        model="text-embedding-3-small",                                       <<<<---------Paid embedding model
        input=text
    )
"""
def get_embedding(s1:str):
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")     <<<<---------Free embedding model
    return model.encode(s1)


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

s100 = "I love machine learning"
s200 = "I enjoy studying artificial intelligence"
s300 = "I love football and basketball"

def find_similarity(s1,s2):
    e1 = get_embedding(s1)
    e2 = get_embedding(s2)
    print("e1", e1)                       # e1 is one vector
    print("e2", e2)                       # e2 is another vector
    similarity = cosine_similarity([e1],[e2])[0][0]          # sklearn is designed to compare multiple vectors with multiple vectors.[0][0] means "give me the value in row 0, column 0."
    return similarity

print(find_similarity(s100, s300))

e1 [-4.36363481e-02 -5.90543598e-02  8.20123255e-02 -1.07671618e-02
  6.11958951e-02 -5.51597774e-02 -2.90431245e-03 -3.67232449e-02
  2.13971473e-02 -7.56046968e-03 -7.17569292e-02  5.08237556e-02
  3.80331837e-02 -1.62503310e-02 -3.21699381e-02  1.52751924e-02
 -4.67936881e-02  1.71293020e-02 -1.20174512e-01 -1.22229196e-01
 -8.08737576e-02  1.70528088e-02 -2.08724383e-02  5.68293780e-03
  1.60141638e-03  2.62672212e-02  2.99522933e-02 -2.75701960e-03
  7.17107113e-03 -6.12753071e-02 -3.61449993e-03  2.48507261e-02
  2.56387275e-02  4.12390791e-02 -1.02098733e-01  8.36903416e-03
  1.39943399e-02  3.09881512e-02  2.43119616e-02  3.08077578e-02
 -4.40565906e-02 -1.38978725e-02  1.30947996e-02  3.64954094e-03
  7.49758035e-02  8.54909718e-02 -5.81433363e-02 -7.58070052e-02
  3.96831818e-02  5.06206974e-02 -8.65324363e-02 -3.23279016e-02
 -2.03663781e-02 -1.62433535e-02 -5.87623715e-02  2.10438799e-02
  6.54708743e-02 -1.25288116e-02  3.35284397e-02 -2.76363920e-02
  2.91945264e-02 -6.91